cosmos/ibc-apps

README.md

Adds the list of [ecosystem apps that we maintain in ibc-go](https://github.com/cosmos/ibc-go#ecosystem). Once this PR is merged we will remove the list from ibc-go and link to the ibc-apps repo instead.
[Rendered view](https://github.com/cosmos/ibc-apps/tree/carlos/readme-add-ecosystem-apps#ecosystem-apps).

docs: add list of ecosystem apps to readme

---

.golangci.yml
modules/async-icq/ibc_module.go
modules/async-icq/ibc_module_test.go
modules/async-icq/keeper/events.go
modules/async-icq/keeper/genesis.go
modules/async-icq/keeper/grpc_query.go
modules/async-icq/keeper/grpc_query_test.go
modules/async-icq/keeper/keeper.go
modules/async-icq/keeper/keeper_test.go
modules/async-icq/keeper/params.go
modules/async-icq/keeper/relay.go
modules/async-icq/keeper/relay_test.go
modules/async-icq/module.go
modules/async-icq/testing/simapp/ante_handler.go
modules/async-icq/testing/simapp/app.go
modules/async-icq/testing/simapp/export.go
modules/async-icq/types/codec.go
modules/async-icq/types/expected_keepers.go
modules/async-icq/types/genesis_test.go
modules/async-icq/types/params_test.go

This PR adds the actual golangci-lint config file to the top level of the repo, this should ensure that the linter is actually running in CI. 
Additionally, I have fixed the few linter errors in `async-icq` that were being thrown.

ci: add golangci-lint config file

---

.github/mergify.yml
README.md
docs/README.md

This PR Integrates Mergify to help keep our maintained branches up to date.
If a PR has the `BACKPORT` label, after it is merged, Mergify will automatically create PR's cherry-picking the merge commit into each of our maintained branches. 
Note: It doesn't matter what branch you target. If you target `release/v5`, It will be backported into `main`, `release/v4`, and `release/v6`
Closes: #7

Integrate Mergify

---

.github/workflows/golangci-lint.yaml

Currently, in our concurrent linter CI, if one linter test fails, any other linter related test does not run or gets cancelled. 
This PR should fix this. Thus allowing all modules to get linted even if one module throws a linting error.

set fail-fast to false for linting CI

---

middleware/packet-forward-middleware/docs/integration.md

A doc containing instructions on how to integrate the packet forward middleware with an existing Cosmos chain. 
I tried to keep this doc similar to the integration doc found [here](https://github.com/cosmos/ibc-go/blob/main/docs/middleware/ics29-fee/integration.md) for the ics29-fee middleware.
Read the rendered doc [here](https://github.com/cosmos/ibc-apps/blob/9da2bda6f007dd8f8b676c9d22f00eb52d831726/middleware/packet-forward-middleware/docs/integration.md)

docs: create an integration guide for the pfm

---

middleware/packet-forward-middleware/docs/integration.md

Missed a typo when handling code review on the integration doc for the PFM

docs: fix typo in pfm integration doc

---

modules/async-icq/ibc_module.go

`OnChanCloseInit` was previously not returning an error which means that proper auth for channel closures was not being enforced.
Many thanks to the folks at SimplyVC who kindly brought this issue to our awareness!!

fix: return proper error on ChanCloseInit

---

.github/mergify.yml

We don't want mergify to label the backported PR's with the `BACKPORT` label, else it will get in a backport loop!
Lets label with `backported` instead.

fix: mergify backport label

---

middleware/packet-forward-middleware/router/ibc_middleware.go

Currently, PFM fails packets that are not `FungibleTokenPacketData`. This means that PFM cannot support IBC apps that don't exclusively use `FungibleTokenPacketData` as the payload format (i.e., ics20-* or the transfer app). Therefore, CosmWasm cannot have PFM in its IBC stack, even though CosmWasm contracts may implement the ics20-* protocol (e.g., cw20-ics20: https://github.com/CosmWasm/cw-plus/tree/HEAD/contracts/cw20-ics20).
This commit fixes the issue by passing the packet forward in the stack rather than failing packets that are not `FungibleTokenPacketData`.
This will allow PFM to support a wider range of IBC apps and will make it possible for CosmWasm to have PFM in its IBC stack, which will improve the interoperability and usability of PFM in the Cosmos ecosystem

Fix PFM to not fail packets that aren't `FungibleTokenPacketData`

---

modules/ibc-hooks/README.md

Add a warning to ensure contracts using IBC hooks don't trust the sender

Add warning to ibc-hooks docs

---

middleware/packet-forward-middleware/packetforward/ibc_middleware.go

This PR exports the `GetReceiver` function. As noted in #131 there are cases where other middleware in the stack may need to make use of this receiver address.
Closes #131

chore: export the GetReceiver function

---

middleware/packet-forward-middleware/packetforward/module.go
middleware/packet-forward-middleware/packetforward/types/params_legacy.go

This PR fixes:
* a proper `fromVersion` argument for migrating from v1 to v2;
* a proper `p.FeePercentage` type for legacy `ParamSetPairs`
**Without theses changes it's impossible to migrate to v7.1.0 version of PFM**

Fix: migrate PFM from 1 to 2

---

middleware/packet-forward-middleware/go.mod
modules/async-icq/go.mod
modules/async-icq/module.go
modules/async-icq/types/params_legacy.go

original ref: https://github.com/cosmos/ibc-apps/pull/141 thanks to the Neutron team !

fix: retract v7.1.0s and fix async icq param migration

---

middleware/packet-forward-middleware/e2e/forward_timeout_test.go
middleware/packet-forward-middleware/packetforward/keeper/keeper.go

Previously we were failing to mint and transfer funds back to the escrow account in the case of a timeout or acknowledgement error but were still issuing the refund back to the sending chain. For forwards that involved IBC assets that were wrapped two or more times, this would result in the escrow account balance being less than the total supply of tokens on the counterparty.

fix: mint and transfer funds back to escrow account on timeout or ack error

---

README.md

`main` looks like it supports ibc-go v8 after https://github.com/cosmos/ibc-apps/pull/152

docs: add `release/v7` branch to maintained branches

---

.codespellrc
.github/markdown-link-check-config.json
.github/workflows/ibc-hooks.yml
.github/workflows/markdown-linter.yaml
.github/workflows/mispell.yml
CONTRIBUTING.md
README.md
middleware/packet-forward-middleware/README.md
middleware/packet-forward-middleware/docs/integration.md
middleware/packet-forward-middleware/packetforward/keeper/keeper.go
middleware/packet-forward-middleware/testing/simapp/params/encoding.go
modules/async-icq/keeper/cache_ctx.go
modules/async-icq/module.go
modules/async-icq/testing/demo-simapp/x/interquery/keeper/msg_server_send_query_all_balances.go
modules/ibc-hooks/README.md
modules/ibc-hooks/wasm_hook.go

closes #178
Fixes all broken links and common spelling issues

CI: link lint + spell check

---

middleware/packet-forward-middleware/e2e/unnecessary_loop_test.go

Add coverage to ensure A->B-(err)>A flow, while not an intended use case, is functional with Mandrake patch.

Add unnecessary loop test

---

middleware/packet-forward-middleware/packetforward/ibc_middleware.go

While looking at the code for PFM, I noticed this log line doesn't match the function name it's in, which could cause confusion for folks who look at logs. This PR should fix it

chore(pfm): update log line to match function name

---

middleware/packet-forward-middleware/docs/integration.md
middleware/packet-forward-middleware/packetforward/ibc_middleware.go
middleware/packet-forward-middleware/packetforward/keeper/keeper.go
middleware/packet-forward-middleware/test/setup.go
middleware/packet-forward-middleware/testing/simapp/app.go

chore(pfm): remove unused `refundTimeout`

---

.github/mergify.yml
README.md

Update the maintained branches table in README.md to reflect that we no longer maintain `release/v5` or `release/v4` due to the associated versions of ibc-go being EOL. Also, update mergify to reflect the currently maintained branches.

docs: update maintained branches table

---

.github/workflows/packet-forward-middleware.yml
middleware/packet-forward-middleware/Makefile
middleware/packet-forward-middleware/e2e/storage_leak_test.go
middleware/packet-forward-middleware/packetforward/ibc_middleware.go

Previously, flight packets were retained in the module's storage after a packet timeout. Now, flight packets are correctly removed when they timeout. An additional test was also added to verify that flight packets are correctly removed and not retained in storage after a timeout.

feat: add storage leak test

---

.github/workflows/packet-forward-middleware.yml
middleware/packet-forward-middleware/Dockerfile
middleware/packet-forward-middleware/e2e/upgrade_test.go
middleware/packet-forward-middleware/packetforward/keeper/migrator.go
middleware/packet-forward-middleware/packetforward/migrations/v3/migrate.go
middleware/packet-forward-middleware/packetforward/migrations/v3/migrate_test.go
middleware/packet-forward-middleware/packetforward/module.go
middleware/packet-forward-middleware/packetforward/types/expected_keepers.go
middleware/packet-forward-middleware/test/mock/bank_keeper.go
middleware/packet-forward-middleware/test/mock/channel_keeper.go
middleware/packet-forward-middleware/test/mock/transfer_keeper.go
middleware/packet-forward-middleware/testing/previous_images/README.md
middleware/packet-forward-middleware/testing/simapp/app.go
middleware/packet-forward-middleware/testing/simapp/upgrades/upgrades.go

Based off #230 to add state migration and upgrade tests
- Migration & tests
- Resolves some CI build issues

feat(pfm): Migration to align expected escrow state

---

modules/rate-limiting/v2/ibc_middleware.go
modules/rate-limiting/v2/ibc_middleware_test.go

Rate limiting expects payloads to always be json marshaled, so it does not currently support ABI or protobuf encoded payloads.
This PR adds support for all encodings to rate limiting v2.

fix: make v2 rate limiting support all encodings

---

modules/rate-limiting/module.go

The `AppModule.BeginBlock` is missing the `error` return type to comply with `HasBeginBlocker`, so it is not being called and the window never get reset.

fix(rate-limiting): interface mismatch on rate limit BeginBlock
